In [5]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib

In [8]:
sql = '''
SELECT "DISTRICT",
       "OCCURRED_ON_DATE",
       "SHOOTING",
       "OFFENSE_DESCRIPTION",
       "STREET"
FROM "b973d8cb-eeb2-4e7e-99da-c92938efc9c0"
WHERE CAST("SHOOTING" AS INT)=1
    '''

In [9]:
bpd_logs = "https://data.boston.gov/api/3/action/datastore_search_sql"

In [10]:
import urllib, requests

In [11]:
url = bpd_logs+"?sql="+urllib.parse.quote(sql)
rows = requests.get( url ).json()

shootings = rows['result']['records']

In [12]:
shootings

[{'DISTRICT': 'B3',
  'OCCURRED_ON_DATE': '2023-02-18 21:43:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'MURDER, NON-NEGLIGENT MANSLAUGHTER',
  'STREET': 'FERMOY HEIGHTS AVE'},
 {'DISTRICT': 'D4',
  'OCCURRED_ON_DATE': '2023-05-24 18:49:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'BALLISTICS EVIDENCE/FOUND',
  'STREET': 'SHAWMUT AVE'},
 {'DISTRICT': 'D4',
  'OCCURRED_ON_DATE': '2023-10-27 12:50:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'ASSAULT - AGGRAVATED',
  'STREET': 'COMMONWEALTH AVE & EXETER ST\nBOSTON  MA 02116\nUNIT'},
 {'DISTRICT': 'B3',
  'OCCURRED_ON_DATE': '2023-01-07 17:51:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'INVESTIGATE PROPERTY',
  'STREET': 'NORWELL ST'},
 {'DISTRICT': 'B2',
  'OCCURRED_ON_DATE': '2023-01-30 17:00:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'ASSAULT - AGGRAVATED',
  'STREET': 'PRENTISS ST'},
 {'DISTRICT': 'C11',
  'OCCURRED_ON_DATE': '2023-10-28 20:56:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'BALLISTICS EVIDENCE/FOUND',
  'STREET': 'TOPLIFF ST'},
 {'DISTRICT': 'B2',
  'OCCURRED_ON_DATE': '2023-10-11 19:21:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'INVESTIGATE PROPERTY',
  'STREET': 'WASHINGTON ST'},
 {'DISTRICT': 'B2',
  'OCCURRED_ON_DATE': '2023-12-16 16:29:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'ASSAULT - AGGRAVATED',
  'STREET': 'QUINCY ST & WARREN ST\nROXBURY  MA 02121\nUNITED STA'},
 {'DISTRICT': 'D14',
  'OCCURRED_ON_DATE': '2025-09-22 22:21:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'STREET': 'JETTE CT'},
 {'DISTRICT': 'E18',
  'OCCURRED_ON_DATE': '2024-05-15 17:07:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'ASSAULT - AGGRAVATED',
  'STREET': 'TAUNTON AVE & RADCLIFFE RD'},
 {'DISTRICT': 'C11',
  'OCCURRED_ON_DATE': '2024-08-12 18:40:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'MURDER, NON-NEGLIGENT MANSLAUGHTER',
  'STREET': 'TRENT ST'},
 {'DISTRICT': 'C11',
  'OCCURRED_ON_DATE': '2023-04-14 19:58:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'BALLISTICS EVIDENCE/FOUND',
  'STREET': 'GENEVA AVE'},
 {'DISTRICT': 'B2',
  'OCCURRED_ON_DATE': '2025-12-08 19:21:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'INVESTIGATE PROPERTY',
  'STREET': 'NORMANDY ST'},
 {'DISTRICT': 'B3',
  'OCCURRED_ON_DATE': '2024-07-10 21:47:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'ASSAULT - AGGRAVATED',
  'STREET': 'GREENWOOD ST'},
 {'DISTRICT': 'A1',
  'OCCURRED_ON_DATE': '2024-05-14 21:45:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'INVESTIGATE PROPERTY',
  'STREET': 'ATLANTIC AVE'},
 {'DISTRICT': 'C11',
  'OCCURRED_ON_DATE': '2023-05-04 00:21:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'BALLISTICS EVIDENCE/FOUND',
  'STREET': 'WASHINGTON ST'},
 {'DISTRICT': 'E13',
  'OCCURRED_ON_DATE': '2024-12-27 19:20:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'WEAPON VIOLATION - CARRY/ POSSESSING/ SALE/ TRAFFICKING/ OTHER',
  'STREET': 'PLANT CT'},
 {'DISTRICT': 'B2',
  'OCCURRED_ON_DATE': '2025-08-06 20:29:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'INVESTIGATE PROPERTY',
  'STREET': 'GREENHEYS ST'},
 {'DISTRICT': 'B3',
  'OCCURRED_ON_DATE': '2025-06-12 23:46:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'ROBBERY',
  'STREET': 'WILDWOOD ST'},
 {'DISTRICT': 'B2',
  'OCCURRED_ON_DATE': '2024-07-02 22:05:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'ASSAULT - AGGRAVATED',
  'STREET': 'CEDAR ST & WASHINGTON ST\nROXBURY, MA 02119\nUNITED '},
 {'DISTRICT': 'B3',
  'OCCURRED_ON_DATE': '2023-06-11 22:31:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'VANDALISM',
  'STREET': 'STRATTON ST'},
 {'DISTRICT': 'B2',
  'OCCURRED_ON_DATE': '2024-05-18 04:02:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'ASSAULT - AGGRAVATED',
  'STREET': 'ABBOTSFORD ST'},
 {'DISTRICT': 'B3',
  'OCCURRED_ON_DATE': '2025-07-24 23:36:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'WEAPON VIOLATION - CARRY/ POSSESSING/ SALE/ TRAFFICKING/ OTHER',
  'STREET': 'WICHITA TER'},
 {'DISTRICT': 'B2',
  'OCCURRED_ON_DATE': '2025-07-17 17:23:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'ASSAULT - AGGRAVATED',
  'STREET': 'BLUE HILL AVE & DUDLEY ST\nROXBURY, MA 02119\nUNITED'},
 {'DISTRICT': 'B2',
  'OCCURRED_ON_DATE': '2023-03-18 00:00:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'INVESTIGATE PROPERTY',
  'STREET': 'COLUMBIA RD'},
 {'DISTRICT': 'B2',
  'OCCURRED_ON_DATE': '2024-11-17 00:14:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'ASSAULT - AGGRAVATED',
  'STREET': 'MADISON PARK CT'},
 {'DISTRICT': 'B3',
  'OCCURRED_ON_DATE': '2023-04-12 00:57:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'INVESTIGATE PROPERTY',
  'STREET': 'GLENARM ST'},
 {'DISTRICT': 'C11',
  'OCCURRED_ON_DATE': '2024-06-28 20:34:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'MURDER, NON-NEGLIGENT MANSLAUGHTER',
  'STREET': 'FIFIELD ST'},
 {'DISTRICT': 'A7',
  'OCCURRED_ON_DATE': '2024-05-16 23:13:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'ASSAULT - AGGRAVATED',
  'STREET': 'MAVERICK ST'},
 {'DISTRICT': 'E5',
  'OCCURRED_ON_DATE': '2024-05-16 22:26:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'FIREARM/WEAPON - FOUND OR CONFISCATED',
  'STREET': 'HAVEY ST'},
 {'DISTRICT': 'B3',
  'OCCURRED_ON_DATE': '2024-12-23 00:18:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'ASSAULT - AGGRAVATED',
  'STREET': 'WILBERT CIRCLE'},
 {'DISTRICT': 'B2',
  'OCCURRED_ON_DATE': '2025-03-12 00:37:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'ASSAULT - AGGRAVATED',
  'STREET': 'DALE ST & PAULDING ST\nROXBURY, MA 02119\nUNITED STA'},
 {'DISTRICT': 'B3',
  'OCCURRED_ON_DATE': '2025-05-17 12:37:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'BALLISTICS EVIDENCE/FOUND',
  'STREET': 'NORFOLK ST'},
 {'DISTRICT': 'B2',
  'OCCURRED_ON_DATE': '2024-05-16 00:12:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'BALLISTICS EVIDENCE/FOUND',
  'STREET': 'LAREDO ST & DEVON ST\nDORCHESTER, MA 02121\nUNITED S'},
 {'DISTRICT': 'B3',
  'OCCURRED_ON_DATE': '2024-05-22 23:37:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'INVESTIGATE PROPERTY',
  'STREET': 'BROWNING AVE'},
 {'DISTRICT': 'A7',
  'OCCURRED_ON_DATE': '2024-05-16 23:04:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'ASSAULT - AGGRAVATED',
  'STREET': 'BRANDYWYNE DR'},
 {'DISTRICT': 'E5',
  'OCCURRED_ON_DATE': '2023-03-10 19:58:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'INVESTIGATE PROPERTY',
  'STREET': 'NEWBURG ST'},
 {'DISTRICT': 'C11',
  'OCCURRED_ON_DATE': '2023-08-05 02:01:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'INVESTIGATE PROPERTY',
  'STREET': 'FULLER ST'},
 {'DISTRICT': 'E18',
  'OCCURRED_ON_DATE': '2024-05-15 10:28:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'VANDALISM',
  'STREET': 'GARFIELD AVE & FARADAY ST\nHYDE PARK, MA 02136\nUNIT'},
 {'DISTRICT': 'C6',
  'OCCURRED_ON_DATE': '2023-10-14 21:06:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'INVESTIGATE PROPERTY',
  'STREET': 'D ST'},
 {'DISTRICT': 'B3',
  'OCCURRED_ON_DATE': '2023-10-14 00:27:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'MURDER, NON-NEGLIGENT MANSLAUGHTER',
  'STREET': 'BLUE HILL AVE'},
 {'DISTRICT': 'D4',
  'OCCURRED_ON_DATE': '2023-02-19 16:45:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'STREET': 'WASHINGTON ST'},
 {'DISTRICT': 'B2',
  'OCCURRED_ON_DATE': '2023-02-19 02:30:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'ASSAULT - SIMPLE',
  'STREET': 'MASCOMA ST'},
 {'DISTRICT': 'D4',
  'OCCURRED_ON_DATE': '2023-02-18 23:34:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'MURDER, NON-NEGLIGIENT MANSLAUGHTER',
  'STREET': 'TREMONT ST'},
 {'DISTRICT': 'C6',
  'OCCURRED_ON_DATE': '2023-12-05 10:57:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'VANDALISM',
  'STREET': 'OLD COLONY AVE'},
 {'DISTRICT': 'C11',
  'OCCURRED_ON_DATE': '2023-10-10 12:10:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'INVESTIGATE PROPERTY',
  'STREET': 'WASHINGTON ST'},
 {'DISTRICT': 'E18',
  'OCCURRED_ON_DATE': '2023-10-10 19:03:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'INVESTIGATE PROPERTY',
  'STREET': 'HYDE PARK AVE & MILTON ST\nBOSTON, MA 02136\nUNITED '},
 {'DISTRICT': 'C11',
  'OCCURRED_ON_DATE': '2023-10-11 04:34:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'INVESTIGATE PROPERTY',
  'STREET': 'RIDGEWOOD ST'},
 {'DISTRICT': 'B3',
  'OCCURRED_ON_DATE': '2023-07-29 00:00:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'VANDALISM',
  'STREET': 'STOCKTON ST'},
 {'DISTRICT': 'D14',
  'OCCURRED_ON_DATE': '2023-10-13 23:23:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'INVESTIGATE PROPERTY',
  'STREET': 'QUINT AVE'},
 {'DISTRICT': 'C11',
  'OCCURRED_ON_DATE': '2023-10-13 14:06:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'MURDER, NON-NEGLIGENT MANSLAUGHTER',
  'STREET': 'CORONA ST'},
 {'DISTRICT': 'D4',
  'OCCURRED_ON_DATE': '2023-10-13 20:39:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'SERVICE TO OTHER AGENCY',
  'STREET': 'E NEWTON ST'},
 {'DISTRICT': 'C11',
  'OCCURRED_ON_DATE': '2023-10-14 17:15:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'BALLISTICS EVIDENCE/FOUND',
  'STREET': 'WASHINGTON ST'},
 {'DISTRICT': 'B3',
  'OCCURRED_ON_DATE': '2023-01-01 17:01:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'BALLISTICS EVIDENCE/FOUND',
  'STREET': 'BLUE HILL AVE'},
 {'DISTRICT': 'B3',
  'OCCURRED_ON_DATE': '2023-01-01 05:55:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'MURDER, NON-NEGLIGENT MANSLAUGHTER',
  'STREET': 'BLUE HILL AVE'},
 {'DISTRICT': 'B2',
  'OCCURRED_ON_DATE': '2023-02-18 19:57:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'ASSAULT - AGGRAVATED',
  'STREET': 'WILLIAMS ST'},
 {'DISTRICT': 'B3',
  'OCCURRED_ON_DATE': '2024-09-27 11:16:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'BALLISTICS EVIDENCE/FOUND',
  'STREET': 'HARVARD ST'},
 {'DISTRICT': 'E5',
  'OCCURRED_ON_DATE': '2023-02-18 11:39:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'INVESTIGATE PROPERTY',
  'STREET': 'WASHINGTON ST'},
 {'DISTRICT': 'D4',
  'OCCURRED_ON_DATE': '2023-02-18 10:52:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'ASSAULT - AGGRAVATED',
  'STREET': 'ALBANY ST'},
 {'DISTRICT': 'D14',
  'OCCURRED_ON_DATE': '2023-12-24 18:27:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'VANDALISM',
  'STREET': 'JETTE CT'},
 {'DISTRICT': 'B2',
  'OCCURRED_ON_DATE': '2024-02-19 03:13:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'INVESTIGATE PROPERTY',
  'STREET': 'MOUNT PLEASANT AVE'},
 {'DISTRICT': 'B2',
  'OCCURRED_ON_DATE': '2023-12-05 04:00:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'VANDALISM',
  'STREET': 'ELM HILL AVE'},
 {'DISTRICT': 'C11',
  'OCCURRED_ON_DATE': '2023-09-10 01:37:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'INVESTIGATE PROPERTY',
  'STREET': 'ROBINSON ST'},
 {'DISTRICT': 'B3',
  'OCCURRED_ON_DATE': '2023-09-09 05:26:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'MURDER, NON-NEGLIGENT MANSLAUGHTER',
  'STREET': 'GREENOCK ST'},
 {'DISTRICT': 'C11',
  'OCCURRED_ON_DATE': '2023-06-03 18:31:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'VANDALISM',
  'STREET': 'HANCOCK ST'},
 {'DISTRICT': 'B2',
  'OCCURRED_ON_DATE': '2023-06-07 00:12:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'BALLISTICS EVIDENCE/FOUND',
  'STREET': 'WOODCLIFF ST'},
 {'DISTRICT': 'B3',
  'OCCURRED_ON_DATE': '2023-06-27 00:17:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'INVESTIGATE PROPERTY',
  'STREET': 'MORTON ST'},
 {'DISTRICT': 'A7',
  'OCCURRED_ON_DATE': '2023-06-07 00:41:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'INVESTIGATE PROPERTY',
  'STREET': 'JEFFRIES ST & SUMNER ST\nEAST BOSTON, MA 02128\nUNIT'},
 {'DISTRICT': 'E18',
  'OCCURRED_ON_DATE': '2023-11-10 00:00:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'BALLISTICS EVIDENCE/FOUND',
  'STREET': 'AUSTIN ST'},
 {'DISTRICT': 'E13',
  'OCCURRED_ON_DATE': '2023-12-07 00:00:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'INVESTIGATE PROPERTY',
  'STREET': 'HEATH ST'},
 {'DISTRICT': 'E13',
  'OCCURRED_ON_DATE': '2023-10-23 21:30:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'ASSAULT - AGGRAVATED',
  'STREET': 'MOZART ST'},
 {'DISTRICT': 'C6',
  'OCCURRED_ON_DATE': '2024-06-28 15:14:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'VANDALISM',
  'STREET': 'GENERAL LAWRENCE J LOGAN WAY'},
 {'DISTRICT': 'C11',
  'OCCURRED_ON_DATE': '2023-10-22 23:46:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'BALLISTICS EVIDENCE/FOUND',
  'STREET': 'BOWDOIN ST'},
 {'DISTRICT': 'B3',
  'OCCURRED_ON_DATE': '2023-09-29 01:04:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'BALLISTICS EVIDENCE/FOUND',
  'STREET': 'MAXWELL ST'},
 {'DISTRICT': 'E18',
  'OCCURRED_ON_DATE': '2023-10-23 20:39:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'BALLISTICS EVIDENCE/FOUND',
  'STREET': 'LEWISTON ST'},
 {'DISTRICT': 'D4',
  'OCCURRED_ON_DATE': '2023-07-13 21:25:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'ASSAULT - AGGRAVATED',
  'STREET': 'SHAWMUT AVE'},
 {'DISTRICT': 'E13',
  'OCCURRED_ON_DATE': '2023-09-11 00:06:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'INVESTIGATE PROPERTY',
  'STREET': 'CENTRE ST'},
 {'DISTRICT': 'B3',
  'OCCURRED_ON_DATE': '2023-06-26 02:49:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'INVESTIGATE PROPERTY',
  'STREET': 'MORTON ST & PLEASANT HILL AVE\nDORCHESTER, MA 02126'},
 {'DISTRICT': 'E5',
  'OCCURRED_ON_DATE': '2023-10-23 19:45:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'M/V - LEAVING SCENE - PROPERTY DAMAGE',
  'STREET': 'WASHINGTON ST'},
 {'DISTRICT': 'B2',
  'OCCURRED_ON_DATE': '2023-10-02 03:43:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'INVESTIGATE PROPERTY',
  'STREET': 'BLUE HILL AVE'},
 {'DISTRICT': 'D4',
  'OCCURRED_ON_DATE': '2023-09-30 23:00:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'ASSAULT - AGGRAVATED',
  'STREET': 'HARRISON AVE'},
 {'DISTRICT': 'C11',
  'OCCURRED_ON_DATE': '2023-05-04 17:44:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'ASSAULT - AGGRAVATED',
  'STREET': 'HOMES AVE'},
 {'DISTRICT': 'E13',
  'OCCURRED_ON_DATE': '2023-07-31 21:28:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'ASSAULT - AGGRAVATED',
  'STREET': 'SCHOOL ST'},
 {'DISTRICT': 'B3',
  'OCCURRED_ON_DATE': '2023-11-09 00:16:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'INVESTIGATE PROPERTY',
  'STREET': 'BLUE HILL AVE'},
 {'DISTRICT': 'B2',
  'OCCURRED_ON_DATE': '2024-05-03 23:08:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'BALLISTICS EVIDENCE/FOUND',
  'STREET': 'ACADEMY CT & ACADEMY RD\nROXBURY, MA 02119\nUNITED S'},
 {'DISTRICT': 'B2',
  'OCCURRED_ON_DATE': '2024-05-03 18:12:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'VANDALISM',
  'STREET': 'BOWER ST'},
 {'DISTRICT': 'A1',
  'OCCURRED_ON_DATE': '2023-07-12 23:05:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'ASSAULT - AGGRAVATED',
  'STREET': 'HANOVER ST'},
 {'DISTRICT': 'E18',
  'OCCURRED_ON_DATE': '2023-07-30 14:21:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'BALLISTICS EVIDENCE/FOUND',
  'STREET': 'WOOD AVE'},
 {'DISTRICT': 'E13',
  'OCCURRED_ON_DATE': '2023-06-24 02:40:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'ASSAULT - AGGRAVATED',
  'STREET': 'MINDEN ST'},
 {'DISTRICT': 'A1',
  'OCCURRED_ON_DATE': '2024-05-22 00:01:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'ASSAULT - AGGRAVATED',
  'STREET': 'WASHINGTON ST'},
 {'DISTRICT': 'E18',
  'OCCURRED_ON_DATE': '2023-09-30 18:34:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'INVESTIGATE PROPERTY',
  'STREET': 'HYDE PARK AVE'},
 {'DISTRICT': 'B3',
  'OCCURRED_ON_DATE': '2023-06-03 22:00:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'BALLISTICS EVIDENCE/FOUND',
  'STREET': 'LORNA RD'},
 {'DISTRICT': 'E13',
  'OCCURRED_ON_DATE': '2023-11-11 00:59:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'INVESTIGATE PROPERTY',
  'STREET': 'WALNUT AVE'},
 {'DISTRICT': 'A15',
  'OCCURRED_ON_DATE': '2023-09-10 00:24:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'VANDALISM',
  'STREET': 'MCNULTY CT'},
 {'DISTRICT': 'D14',
  'OCCURRED_ON_DATE': '2023-07-13 02:25:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'INVESTIGATE PROPERTY',
  'STREET': 'FANEUIL ST & BRACKETT ST'},
 {'DISTRICT': 'C11',
  'OCCURRED_ON_DATE': '2023-05-09 01:22:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'INVESTIGATE PROPERTY',
  'STREET': 'WASHINGTON ST'},
 {'DISTRICT': 'B3',
  'OCCURRED_ON_DATE': '2023-10-23 18:10:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'BALLISTICS EVIDENCE/FOUND',
  'STREET': 'CANTERBURY LN & MORTON ST\nDORCHESTER, MA 02121\nUNI'},
 {'DISTRICT': 'B2',
  'OCCURRED_ON_DATE': '2023-10-24 05:20:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'INVESTIGATE PROPERTY',
  'STREET': 'IRWIN AVE'},
 {'DISTRICT': 'C11',
  'OCCURRED_ON_DATE': '2024-07-27 04:15:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'INVESTIGATE PROPERTY',
  'STREET': 'BENTHAM RD'},
 {'DISTRICT': 'B3',
  'OCCURRED_ON_DATE': '2024-06-09 22:59:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'ASSAULT - AGGRAVATED',
  'STREET': 'ASTORIA ST'},
 {'DISTRICT': 'B2',
  'OCCURRED_ON_DATE': '2023-07-31 23:24:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'VANDALISM',
  'STREET': 'ELM HILL AVE'},
 {'DISTRICT': 'C11',
  'OCCURRED_ON_DATE': '2023-11-10 02:59:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'INVESTIGATE PROPERTY',
  'STREET': 'WELLES AVE'},
 {'DISTRICT': 'B2',
  'OCCURRED_ON_DATE': '2023-07-30 19:47:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'MURDER, NON-NEGLIGENT MANSLAUGHTER',
  'STREET': 'BLUE HILL AVENUE'},
 {'DISTRICT': 'B3',
  'OCCURRED_ON_DATE': '2023-12-24 00:00:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'ASSAULT - AGGRAVATED',
  'STREET': 'RIPLEY RD'},
 {'DISTRICT': 'B2',
  'OCCURRED_ON_DATE': '2024-01-28 04:56:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'INVESTIGATE PROPERTY',
  'STREET': 'ANNUNCIATION RD'},
 {'DISTRICT': 'B3',
  'OCCURRED_ON_DATE': '2024-02-18 06:23:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'BALLISTICS EVIDENCE/FOUND',
  'STREET': 'FAUNCE RD'},
 {'DISTRICT': 'E13',
  'OCCURRED_ON_DATE': '2023-06-24 21:43:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'INVESTIGATE PROPERTY',
  'STREET': 'W WALNUT PARK & COLUMBUS AVE'},
 {'DISTRICT': 'B2',
  'OCCURRED_ON_DATE': '2024-06-28 16:47:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'VANDALISM',
  'STREET': 'MARCELLA ST & VALE ST\nROXBURY, MA 02119\nUNITED STA'},
 {'DISTRICT': 'D4',
  'OCCURRED_ON_DATE': '2024-05-04 23:18:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'INVESTIGATE PERSON',
  'STREET': 'COMMONWEALTH AVE & KENMORE ST\nBOSTON, MA 02215\nUNI'},
 {'DISTRICT': 'B3',
  'OCCURRED_ON_DATE': '2023-07-13 14:05:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'MURDER, NON-NEGLIGENT MANSLAUGHTER',
  'STREET': 'FESSENDEN ST'},
 {'DISTRICT': 'B3',
  'OCCURRED_ON_DATE': '2023-07-14 00:37:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'VANDALISM',
  'STREET': 'MILTON AVE'},
 {'DISTRICT': 'A15',
  'OCCURRED_ON_DATE': '2024-06-08 00:00:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'INVESTIGATE PROPERTY',
  'STREET': 'OLD IRONSIDES WAY'},
 {'DISTRICT': 'E18',
  'OCCURRED_ON_DATE': '2024-02-19 07:44:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'INVESTIGATE PROPERTY',
  'STREET': 'TILESTON ST'},
 {'DISTRICT': 'C11',
  'OCCURRED_ON_DATE': '2024-01-12 01:13:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'BALLISTICS EVIDENCE/FOUND',
  'STREET': 'BERRY ST'},
 {'DISTRICT': 'B3',
  'OCCURRED_ON_DATE': '2023-07-12 23:49:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'INVESTIGATE PROPERTY',
  'STREET': 'COLONIAL AVE'},
 {'DISTRICT': 'B2',
  'OCCURRED_ON_DATE': '2024-06-28 17:28:00+00',
  'SHOOTING': '1',
  'OFFENSE_DESCRIPTION': 'WEAPON VIOLATION - CARRY/ POSSESSING/ SALE/ TRAFFICKING/ OTHER',
  'STREET': 'COLUMBUS AVE & CEDAR ST\nROXBURY, MA 02119\nUNITED S'},
 {'DISTRICT': 'E18',

In [13]:
import pandas as pd

# Convert the list of dictionaries to a pandas DataFrame
df_shootings = pd.DataFrame(shootings)

In [14]:
# Group by 'STREET' and count the number of shootings, then get the top 10
top_10_streets = df_shootings['STREET'].value_counts().nlargest(10)
display("Top 10 Streets with the Most Shootings:", top_10_streets.to_frame())

'Top 10 Streets with the Most Shootings:'

                count
STREET
WASHINGTON ST      70
BLUE HILL AVE      47
CENTRE ST          38
COLUMBIA RD        25
DORCHESTER AVE     23
DUDLEY ST          21
WALNUT AVE         18
GENEVA AVE         17
BOWDOIN ST         15
TALBOT AVE         15

In [20]:
display("Streets and Districts for Top 10 Streets:", df_top_streets[['STREET', 'DISTRICT']].drop_duplicates().sort_values(by='STREET'))

'Streets and Districts for Top 10 Streets:'

              STREET DISTRICT
40     BLUE HILL AVE       B3
79     BLUE HILL AVE       B2
1509      BOWDOIN ST       A1
72        BOWDOIN ST      C11
491        CENTRE ST       E5
354        CENTRE ST      C11
1486       CENTRE ST       B2
76         CENTRE ST      E13
890      COLUMBIA RD       B3
797      COLUMBIA RD       C6
182      COLUMBIA RD      C11
24       COLUMBIA RD       B2
199   DORCHESTER AVE      C11
225        DUDLEY ST       B2
11        GENEVA AVE      C11
350       GENEVA AVE       B2
159       TALBOT AVE       B3
319       TALBOT AVE      C11
92        WALNUT AVE      E13
238       WALNUT AVE       B2
857    WASHINGTON ST      D14
15     WASHINGTON ST      C11
41     WASHINGTON ST       D4
384    WASHINGTON ST      E13
89     WASHINGTON ST       A1
57     WASHINGTON ST       E5
632    WASHINGTON ST       B3
6      WASHINGTON ST       B2

NameError: name 'AI' is not defined